from pathlib import Path
p = Path('/home/trstyq/code/etl-platform/etl-main-app/src/main/java/com/etl/sfdc/etl/controller/ETLController.java')
text = p.read_text()
replacements = [
("""            if (e.getMessage() != null && e.getMessage().contains(\"401\")) {\n                String refreshedAccessToken = tokenManager.refreshAccessToken(session, context.org);\n                if (refreshedAccessToken != null && context.org != null) {\n                    SalesforceTokenManager.RefreshResult refreshPair = tokenManager.refreshTokenPair(session, context.org);\n                    if (refreshPair != null) {\n                        salesforceOrgService.persistTokens(context.org.getOrgKey(), refreshPair.accessToken(), refreshPair.refreshToken());\n                        context.accessToken = refreshPair.accessToken();\n                        tokenManager.setTokenPair(session, refreshPair.accessToken(), refreshPair.refreshToken());\n                    } else {\n                        context.accessToken = refreshedAccessToken;\n                    }\n                    ingestionStatusByObject = etlService.getIngestionStatusByObject(context.accessToken, context.myDomain);\n                } else {\n                    response.sendRedirect(\"/etl/orgs?message=need_org_auth&reason=refresh_failed\" + (context.org != null ? \"&orgKey=\" + context.org.getOrgKey() : \"\"));\n                    return null;\n                }\n            } else {\n""",
"""            if (e.getMessage() != null && e.getMessage().contains(\"401\")) {\n                String refreshedAccessToken = refreshAccessTokenIfNeeded(context, session);\n                if (refreshedAccessToken != null) {\n                    ingestionStatusByObject = etlService.getIngestionStatusByObject(refreshedAccessToken, context.myDomain);\n                } else {\n                    response.sendRedirect(\"/etl/orgs?message=need_org_auth&reason=refresh_failed\" + (context.org != null ? \"&orgKey=\" + context.org.getOrgKey() : \"\"));\n                    return null;\n                }\n            } else {\n"""),
("""            if (e.getMessage() != null && e.getMessage().contains(\"401\")) {\n                String refreshedAccessToken = tokenManager.refreshAccessToken(session, context.org);\n                if (refreshedAccessToken != null && context.org != null) {\n                    SalesforceTokenManager.RefreshResult refreshPair = tokenManager.refreshTokenPair(session, context.org);\n                    if (refreshPair != null) {\n                        salesforceOrgService.persistTokens(context.org.getOrgKey(), refreshPair.accessToken(), refreshPair.refreshToken());\n                        context.accessToken = refreshPair.accessToken();\n                        tokenManager.setTokenPair(session, refreshPair.accessToken(), refreshPair.refreshToken());\n                    } else {\n                        context.accessToken = refreshedAccessToken;\n                    }\n                    etlService.syncRoutingRegistryFromSalesforce(context.accessToken, actor, context.myDomain);\n                } else {\n                    response.sendRedirect(\"/etl/orgs?message=need_org_auth&reason=refresh_failed\" + (context.org != null ? \"&orgKey=\" + context.org.getOrgKey() : \"\"));\n                    return null;\n                }\n            } else {\n""",
"""            if (e.getMessage() != null && e.getMessage().contains(\"401\")) {\n                String refreshedAccessToken = refreshAccessTokenIfNeeded(context, session);\n                if (refreshedAccessToken != null) {\n                    etlService.syncRoutingRegistryFromSalesforce(refreshedAccessToken, actor, context.myDomain);\n                } else {\n                    response.sendRedirect(\"/etl/orgs?message=need_org_auth&reason=refresh_failed\" + (context.org != null ? \"&orgKey=\" + context.org.getOrgKey() : \"\"));\n                    return null;\n                }\n            } else {\n"""),
("""                if (e.getMessage() != null && e.getMessage().contains(\"401\")) {\n                    String refreshedAccessToken = tokenManager.refreshAccessToken(session, context.org);\n                    if (refreshedAccessToken != null && context.org != null) {\n                        SalesforceTokenManager.RefreshResult refreshPair = tokenManager.refreshTokenPair(session, context.org);\n                        if (refreshPair != null) {\n                            salesforceOrgService.persistTokens(context.org.getOrgKey(), refreshPair.accessToken(), refreshPair.refreshToken());\n                            context.accessToken = refreshPair.accessToken();\n                            tokenManager.setTokenPair(session, refreshPair.accessToken(), refreshPair.refreshToken());\n                        } else {\n                            context.accessToken = refreshedAccessToken;\n                        }\n                        etlService.syncRoutingRegistryFromSalesforce(context.accessToken, currentActor(), context.myDomain);\n                    } else {\n                        response.sendRedirect(\"/etl/orgs?message=need_org_auth&reason=refresh_failed\" + (context.org != null ? \"&orgKey=\" + context.org.getOrgKey() : \"\"));\n                        return null;\n                    }\n                } else {\n""",
"""                if (e.getMessage() != null && e.getMessage().contains(\"401\")) {\n                    String refreshedAccessToken = refreshAccessTokenIfNeeded(context, session);\n                    if (refreshedAccessToken != null) {\n                        etlService.syncRoutingRegistryFromSalesforce(refreshedAccessToken, currentActor(), context.myDomain);\n                    } else {\n                        response.sendRedirect(\"/etl/orgs?message=need_org_auth&reason=refresh_failed\" + (context.org != null ? \"&orgKey=\" + context.org.getOrgKey() : \"\"));\n                        return null;\n                    }\n                } else {\n"""),
("""                if (e.getMessage() != null && e.getMessage().contains(\"401\")) {\n                    String refreshedAccessToken = tokenManager.refreshAccessToken(session, context.org);\n                    if (refreshedAccessToken == null && context.org != null) {\n                        response.sendRedirect(\"/etl/orgs?message=need_org_auth&reason=refresh_failed&orgKey=\" + context.org.getOrgKey());\n                        return null;\n                    }\n                    if (refreshedAccessToken != null && context.org != null) {\n                        SalesforceTokenManager.RefreshResult refreshPair = tokenManager.refreshTokenPair(session, context.org);\n                        if (refreshPair != null) {\n                            salesforceOrgService.persistTokens(context.org.getOrgKey(), refreshPair.accessToken(), refreshPair.refreshToken());\n                            context.accessToken = refreshPair.accessToken();\n                            tokenManager.setTokenPair(session, refreshPair.accessToken(), refreshPair.refreshToken());\n                        } else {\n                            context.accessToken = refreshedAccessToken;\n                        }\n                        tokenManager.setActiveOrg(session, context.org.getOrgKey());\n                    }\n                } else {\n""",
"""                if (e.getMessage() != null && e.getMessage().contains(\"401\")) {\n                    String refreshedAccessToken = refreshAccessTokenIfNeeded(context, session);\n                    if (refreshedAccessToken == null && context.org != null) {\n                        response.sendRedirect(\"/etl/orgs?message=need_org_auth&reason=refresh_failed&orgKey=\" + context.org.getOrgKey());\n                        return null;\n                    }\n                    if (refreshedAccessToken != null && context.org != null) {\n                        tokenManager.setActiveOrg(session, context.org.getOrgKey());\n                    }\n                } else {\n"""),
("""                String refreshedAccessToken = tokenManager.refreshAccessToken(session, context.org);\n                if (refreshedAccessToken == null) {\n                    response.sendRedirect(\"/etl/orgs?message=need_org_auth&reason=refresh_failed&orgKey=\" + context.org.getOrgKey());\n                    return null;\n                }\n                SalesforceTokenManager.RefreshResult refreshPair = tokenManager.refreshTokenPair(session, context.org);\n                if (refreshPair != null) {\n                    salesforceOrgService.persistTokens(context.org.getOrgKey(), refreshPair.accessToken(), refreshPair.refreshToken());\n                    context.accessToken = refreshPair.accessToken();\n                    tokenManager.setTokenPair(session, refreshPair.accessToken(), refreshPair.refreshToken());\n                } else {\n                    context.accessToken = refreshedAccessToken;\n                }\n""",
"""                String refreshedAccessToken = refreshAccessTokenIfNeeded(context, session);\n                if (refreshedAccessToken == null) {\n                    response.sendRedirect(\"/etl/orgs?message=need_org_auth&reason=refresh_failed&orgKey=\" + context.org.getOrgKey());\n                    return null;\n                }\n"""),
("""            if (e.getMessage() != null && e.getMessage().contains(\"401\") && context.org != null) {\n                String refreshedAccessToken = tokenManager.refreshAccessToken(session, context.org);\n                if (refreshedAccessToken != null) {\n                    SalesforceTokenManager.RefreshResult refreshPair = tokenManager.refreshTokenPair(session, context.org);\n                    if (refreshPair != null) {\n                        salesforceOrgService.persistTokens(context.org.getOrgKey(), refreshPair.accessToken(), refreshPair.refreshToken());\n                        tokenManager.setActiveOrg(session, context.org.getOrgKey());\n                        tokenManager.setTokenPair(session, refreshPair.accessToken(), refreshPair.refreshToken());\n                        context.accessToken = refreshPair.accessToken();\n                    }\n                    Map<String, Object> retrySummary = etlService.releaseObject(\n                            sanitizedObject,\n                            sanitizedMode,\n                            (refreshPair == null ? refreshedAccessToken : refreshPair.accessToken()),\n                            actor,\n                            context.myDomain,\n                            context.org.getOrgKey()\n                    );\n""",
"""            if (e.getMessage() != null && e.getMessage().contains(\"401\") && context.org != null) {\n                String refreshedAccessToken = refreshAccessTokenIfNeeded(context, session);\n                if (refreshedAccessToken != null) {\n                    Map<String, Object> retrySummary = etlService.releaseObject(\n                            sanitizedObject,\n                            sanitizedMode,\n                            refreshedAccessToken,\n                            actor,\n                            context.myDomain,\n                            context.org.getOrgKey()\n                    );\n"""),
("""            SalesforceTokenManager.RefreshResult refreshPair = tokenManager.refreshTokenPair(session, context.org);\n            if (refreshPair == null) {\n                response.sendRedirect(\"/etl/orgs?message=need_org_auth&reason=refresh_failed\" + (context.org != null ? \"&orgKey=\" + context.org.getOrgKey() : \"\"));\n                return List.of();\n            }\n\n            if (context.org != null) {\n                salesforceOrgService.persistTokens(context.org.getOrgKey(), refreshPair.accessToken(), refreshPair.refreshToken());\n                context.accessToken = refreshPair.accessToken();\n                tokenManager.setTokenPair(session, refreshPair.accessToken(), refreshPair.refreshToken());\n            }\n""",
"""            String refreshedAccessToken = refreshAccessTokenIfNeeded(context, session);\n            if (refreshedAccessToken == null) {\n                response.sendRedirect(\"/etl/orgs?message=need_org_auth&reason=refresh_failed\" + (context.org != null ? \"&orgKey=\" + context.org.getOrgKey() : \"\"));\n                return List.of();\n            }\n"""),
("""            String refreshed = tokenManager.refreshAccessToken(session, context.org);\n            if (refreshed != null) {\n                SalesforceTokenManager.RefreshResult refreshPair = tokenManager.refreshTokenPair(session, context.org);\n                if (refreshPair != null) {\n                    salesforceOrgService.persistTokens(orgKey, refreshPair.accessToken(), refreshPair.refreshToken());\n                    tokenManager.setActiveOrg(session, orgKey);\n                    tokenManager.setTokenPair(session, refreshPair.accessToken(), refreshPair.refreshToken());\n                    context.accessToken = refreshPair.accessToken();\n                    return refreshPair.accessToken();\n                }\n                tokenManager.setAccessToken(session, refreshed);\n                context.accessToken = refreshed;\n                return refreshed;\n            }\n""",
"""            String refreshed = refreshAccessTokenIfNeeded(context, session);\n            if (refreshed != null) {\n                return refreshed;\n            }\n""")
]
count = 0
for old, new in replacements:
    if old in text:
        text = text.replace(old, new)
        count += 1
p.write_text(text)
print(count)
